### ISSUE TITLE
Comment from Joshua

### ISSUE THREAD

**Issue by b-joshua** [rotemberda/rotemberda.github.io#2]
Very nice layout, Rotem! Your site is looking very professional. If you're going to list your hands-on experience, consider including links to the labs where you learned these skills. You might also want to make "Contact" its own separate header rather than a sub-header within "About Me". I suggest you add a line of text explaining what the two links at the bottom of the page are, since at the moment they stand alone with no explanation. Overall, your website is looking great! Well done.

**Comment by rotemberda** [comment]
Thanks for the constructive suggestions! I updated my site.

**Comment by b-joshua** [comment]
@hadarklimovski
